frase = 'O mijão é lindo'
print('A frase tem', len(frase),'caracteres')
print(frase[:10])
print(frase[1:15])
print(frase[::3])
print(frase.title())
print('Existe {} letras o e {} O'.format(frase.count('o'),frase.count('O')))
print(frase.upper())
print(frase.replace('lindo','bonito'))
print(frase.find('lin'))
print(frase[0])
print('mijão' in frase)
dividido = frase.split()
print(dividido[0])
print(dividido[1])
print('-'.join(dividido))